[package]
name = "tributary-rs"
version = "0.1.0"
authors = ["Tim Paine <t.paine154@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

[features]
coverage = []
