name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run on sunday nights
    - cron:  '0 0 * * 0'

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        event-name: [push]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: clippy
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Install dependencies
      run: |
        make dev

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        cargo test -- -Z unstable-options --format json | cargo2junit > results.xml;
        zip -0 ccov.zip `find . \( -name "$tributary*.gc*" \) -print`;
        grcov ccov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" --ignore "tests/*" -o lcov.info;
      env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
          RUSTDOCFLAGS: -Cpanic=abort
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: results.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload to CodeCov
      uses: codecov/codecov-action@v1
      with:
        files: ./lcov.info
        fail_ci_if_error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
